#!/bin/bash
generate_test () {
   block_size=$1; count_blocks=$2; files_to_archive=$3
   expectDirSize=$((512*1024))
   currdir=$(pwd)
   mkdir -p $currdir/log_files
   dirsize=$(du -sk $currdir/log_files | awk '{print $1}')
   cnt=0
   while [ $expectDirSize -ge $dirsize ]; 
   do
	   dd if=/dev/urandom of=$currdir/log_files/file_$cnt bs=${block_size}M count=$count_blocks > /dev/null
	   dirsize=$(du -sk $currdir/log_files | awk '{print $1}')
	   cnt=$((cnt + 1))

   done
   echo "log dir: `ls $currdir/log_files`"
   ./laba $currdir $files_to_archive
   echo "log dir after archieving files:"
   ls $currdir/log_files

}
generate_test 1 10 30
