#!/bin/bash

workingDir=$1
n=$2
files_dir=$3
sizeof=$(df -k $workingDir/$files_dir | awk 'NR==2 {print $2}')
workingDirSize=$(du -sk $workingDir | awk '{print $1}')
percentage=$(echo "scale=6; $workingDirSize * 100 / $sizeof" | bc)
mkdir -p $workingDir/backup_$files_dir

if (( $(echo "$percentage >= 1" | bc -l) ));
then 
   files=$(find $workingDir/$files_dir -maxdepth 1 -type f -printf '%T+ %p\n' | sort | head -n $n | awk '{print $2}')

   if [ -n "$files" ]; then
      mkdir -p ./temp_dir
      cnt=0
      for file in $files; do
	      mv "$file" ./temp_dir/file_$cnt
	      cnt=$(( cnt + 1 ))
      done
      tar czf $workingDir/backup_${files_dir}/$(date +%Y%m%d_%H%M%S).tar.gz ./temp_dir
      if [ $? -eq 0 ]; then
	rm -r ./temp_dir
      echo "$cnt files archived in ./backup/"
      ls $workingDir/backup_$files_dir
      else
      	echo "error while archiving files"
      fi
  fi
 else 
 echo "not enough space to archive"
fi

